### ISSUE TITLE
When default profile is only profile set up or no profiles are configured, awspp dies ungracefully

### ISSUE THREAD

**Issue by sjsadowski** [abyss/awsp-plus#10]
**Summary:**
If the config file does not exist or only contains [default], the script errors in an ugly manner

```
AWS Profile Switcher Plus
No profiles found.
Refer to this guide for help on setting up a new AWS profile:
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html
Error: TypeError: Cannot read property 'profile' of undefined
    at /home/ssadowski/.local/.npm/lib/node_modules/awsp-plus/index.js:64:46
    at new Promise (<anonymous>)
    at writeToConfig (/home/ssadowski/.local/.npm/lib/node_modules/awsp-plus/index.js:63:10)
cat: /home/ssadowski/.awsp: No such file or directory
```

**Expected result:**
If default isn't available, echo only the 'No profiles found' message with link, if default is available, allow user to select it

**Comment by abyss** [comment]
This version is being archived. This issue is fixed in https://github.com/abyss/go-awsp.
